### ISSUE TITLE
Yanked dependancies 

### ISSUE THREAD

**Issue by davidmckennirey** [postrequest/xeca#2]
This tool is un-buildable with its current dependencies. Specifically, the dependancies on `aes-soft` (which is now yanked) and `block-modes` (which requires the `block-cipher-trait` package that has been yanked). It appears that updating the dependencies in Cargo.toml does not solve the issue, because the newer versions of these libraries have implementation differences that cause the build to fail.

**Comment by postrequest** [comment]
Hi @davidmckennirey ,

Thanks for raising this issue, updates have been pushed to master and the tool should work as intended.

Happy hunting!

**Comment by davidmckennirey** [comment]
Can confirm that it builds properly again. Thanks for the fix!
